### ISSUE TITLE
游侠签到

### ISSUE THREAD

**Issue by szdongjun** [lksky8/sign-ql#12]
游侠签到是坏了吗?登录可以,但状态是没签也说已签,而且任务出错
【开始一周签到】
查询签到状态失败
TypeError: Cannot read properties of undefined (reading 'signday')
    at /ql/scripts/yxw.js:238:47
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/yxw.js:511:5722)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by lksky8** [comment]
我重新上传一个新的js试试

**Comment by lksky8** [comment]
不知道是否账号问题，我这边一切正常

**Comment by lksky8** [comment]
## 开始执行... 2023-03-31 08:54:29


ߔ䤻this.name}, 开始!


=============================================    
脚本执行 - 北京时间(UTC+8)：2023/3/31 08:54:29 
=============================================


=================== 共找到 1 个账号 ===================

========= 开始【第 1 个账号】=========

【开始登录】
登录成功,JDPushService

【开始查询签到状态】
签到成功，获得金币:10

【开始一周签到】
周签成功
第4天完成签到，第七天可以抽奖领取奖励

账号[JDPushService]总金币：123830个，可用现金：1412
Bark APP发送通知消息成功🎉


ߔ䤻this.name}, 结束! ߕ려{s} 秒


## 执行结束... 2023-03-31 08:54:42 耗时 13 秒

**Comment by szdongjun** [comment]
新脚本也试了,一样,不知是不是新注册的不行?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lksky8/sign-ql"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月31日(星期五) 上午10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lksky8/sign-ql] 游侠签到 (Issue #12)





 
不知道是否账号问题，我这边一切正常

**Comment by szdongjun** [comment]
好像没周活动
![6ee912404be08841bcb5467c263fc8d](https://user-images.githubusercontent.com/77103214/229256903-7755eac3-5004-4321-a90a-dca3c1db9596.jpg)
![912d73d475f71bb9c82ea600b22c63f](https://user-images.githubusercontent.com/77103214/229256919-bca51b12-7a50-490d-acb5-00858ffc1f6b.jpg)

**Comment by lksky8** [comment]
let weeksingday = result.data.signday
在这段代码上面加一个log(data)
然后跑一下脚本看看输出什么

**Comment by szdongjun** [comment]
【开始一周签到】 查询签到状态失败 {"status":0,"msg":"\u975e\u6cd5\u64cd\u4f5c"} TypeError: Cannot read properties of undefined (reading 'signday')     at /ql/scripts/yxw.js:239:47     at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/yxw.js:512:5722)     at processTicksAndRejections (node:internal/process/task_queues:96:5)


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lksky8/sign-ql"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月1日(星期六) 上午8:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lksky8/sign-ql] 游侠签到 (Issue #12)





 
let weeksingday = result.data.signday
 在这段代码上面加一个log(data)
 然后跑一下脚本看看输出什么

**Comment by szdongjun** [comment]
添加后显示以上信息

**Comment by szdongjun** [comment]
【开始一周签到】
查询签到状态失败
TypeError: Cannot read properties of undefined (reading 'signday')
    at /ql/scripts/yxw.js:238:47
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/yxw.js:511:5722)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
账号[游侠20231]总金币：30个，可用现金：0

**Comment by lksky8** [comment]
在修了

**Comment by szdongjun** [comment]
现金也不显示,我兑换了有的

**Comment by szdongjun** [comment]
好的,我去睡一下,还没睡呢,搞了一晚上,还绑了Steam,都不行,麻烦大佬了

**Comment by lksky8** [comment]
已修复

**Comment by szdongjun** [comment]
好了,感谢大佬,有qmm签到吗?

**Comment by lksky8** [comment]
有是有，只是没打算写，脚本在另一个签到面板上
https://github.com/lksky8/sign-har/blob/main/%E5%88%B8%E5%A6%88%E5%A6%88%E6%AF%8F%E6%97%A5%E7%AD%BE%E5%88%B0.har

**Comment by szdongjun** [comment]
这个怎么用在青龙上?文件不是js,还有游侠新手签到是做了,但没领币




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lksky8/sign-ql"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月2日(星期天) 上午8:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lksky8/sign-ql] 游侠签到 (Issue #12)





 
有是有，只是没打算写，脚本在另一个签到面板上
 https://github.com/lksky8/sign-har/blob/main/%E5%88%B8%E5%A6%88%E5%A6%88%E6%AF%8F%E6%97%A5%E7%AD%BE%E5%88%B0.har

**Comment by lksky8** [comment]
领的话，手动操作，没写进去，因为这个活动签一个月就没。青龙有空再写

**Comment by szdongjun** [comment]
好的,谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lksky8/sign-ql"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月2日(星期天) 下午3:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lksky8/sign-ql] 游侠签到 (Issue #12)





 
领的话，手动操作，没写进去，因为这个活动签一个月就没。青龙有空再写

**Comment by szdongjun** [comment]
大佬，有qmm提现吗？本来想自已试试但没哪技朮和学问
