### ISSUE TITLE
一直到这边出错，不知道是不是果园抓的不对？？

### ISSUE THREAD

**Issue by lala123963** [lksky8/sign-ql#2]
【APP签到】
签到成功，获得：5积分，已经签到了89天
开始鱼塘任务
【鱼塘-连续签到】
任务已完成
【鱼塘-每日签到】
任务已完成
【鱼塘-三餐开福袋】
还没到领取时间，请在7-9；10-12；16-18这三个时间段内操作
【鱼塘-去翻牌一次】
饲料不足，翻牌失败
【鱼塘-浏览商品得饲料】
任务已完成
【鱼塘-浏览宝妈严选得饲料】
任务已完成
获取任务数据成功
【鱼塘-领饲料瓶】
已经领取过该奖励
【鱼塘-参与天天翻牌活动】领取奖励
已经领取过该奖励
【果园-去鱼塘喂食一次】领取任务
【去鱼塘喂食一次】任务已完成
目前鱼饲料：2g
饲料不足10g或者饲料瓶已经满了，停止喂养，可手动操作
【鱼塘-去完成可能失败的任务】
已经领取过该奖励
已经领取过该奖励
ReferenceError: fpid2 is not defined
    at /ql/data/scripts/lala123963_lk/ddmc.js:131:21

🔔叮咚买菜, 结束! 🕛 30.012 秒

**Comment by lksky8** [comment]
已修复

**Comment by lala123963** [comment]
【账号】XXXXX_X...|登录成功，cookie有效

131行 
 await rewardtask(fpid2,0)  
报错 
ReferenceError: fpid2 is not defined
    at /ql/data/scripts/text.js:131:21
173行
await doachieve('FEED_N_TIMES',1)
报错
获取任务数据失败，可能是cookies失效

**Comment by lksky8** [comment]
已修复
